# sudo docker run -itd --rm --name n8n -p 5678:5678 -v n8n_data:/home/node/.n8n docker.n8n.io/n8nio/n8n


services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n 
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n 

    restart: unless-stopped
    networks:
      - n8n_net

  autoscraper:
    build: .
    container_name: autoscraper
    ports:
      - 8000:8000
    volumes:
      - .:/app 
    restart: unless-stopped
    networks:
      - n8n_net


volumes:
  n8n_data:

networks:
  n8n_net:
    driver: bridge